fix(docker): aplicar perfil de banco de teste

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,54 +1,89 @@
 name: QA Pipeline
 
 on:
-  pull_request:
-    branches: [main]
+    pull_request:
+        branches: [main]
 
 jobs:
-  build-and-analyze:
-    name: Build, Test & Security Analysis
-    runs-on: ubuntu-latest
-    environment: production
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0 
+    build-and-analyze:
+        name: Build, Test & Security Analysis
+        runs-on: ubuntu-latest
+        environment: production
+        steps:
+            - name: Checkout code
+              uses: actions/checkout@v4
+              with:
+                  fetch-depth: 0
 
-      - name: Set up Java 21
-        uses: actions/setup-java@v4
-        with:
-          java-version: "21"
-          distribution: "temurin"
-          cache: "maven"
+            - name: Check Branch Name
+              run: |
+                  BRANCH_NAME="${{ github.head_ref }}"
+                  # Regex: Permite letras, números, barras, hifens e underscores. 
+                  # Bloqueia acentos, espaços e símbolos estranhos.
+                  ALLOWED_REGEX="^[a-zA-Z0-9\/\-_]+$"
 
-      - name: Starting MongoDB for Testing
-        run: docker compose --profile db up -d
+                  if [[ ! $BRANCH_NAME =~ $ALLOWED_REGEX ]]; then
+                  echo "ERROR: O nome da branch '$BRANCH_NAME' contém caracteres especiais!"
+                  echo "Use apenas letras, números, '/', '-' ou '_'."
+                  exit 1
+                  fi
 
-      - name: Build, Test & Sonar (Driver Service)
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-        run: |
-          cd driver-service
-          mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
-          -Dsonar.projectKey=joljolionn_sumus_driver-service \
-          -Dsonar.organization=joljolionn \
-          -Dsonar.host.url=https://sonarcloud.io \
-          -Dsonar.qualitygate.wait=false
+            - name: Validate Each Commit Message
+              run: |
+                  BASE_SHA=${{ github.event.pull_request.base.sha }}
+                  HEAD_SHA=${{ github.event.pull_request.head.sha }}
 
-      - name: Build, Test & Sonar (Passenger Service)
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-        run: |
-          cd passenger-service
-          mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
-          -Dsonar.projectKey=joljolionn_sumus_passenger-service \
-          -Dsonar.organization=joljolionn \
-          -Dsonar.host.url=https://sonarcloud.io \
-          -Dsonar.qualitygate.wait=false
+                  COMMITS=$(git rev-list $BASE_SHA..$HEAD_SHA)
 
-      - name: Stop containers
-        if: always()
-        run: docker compose --profile db down
+                  # Regex para o formato: foo(bar): bass
+                  REGEX="^[a-z]+(\([a-z0-9-]+\))?: .+"
+
+                  for COMMIT in $COMMITS; do
+                    MSG=$(git log -1 --pretty=%B $COMMIT)
+                    
+                    if [[ ! $MSG =~ $REGEX ]]; then
+                      echo "ERRO: Formato inválido no commit $COMMIT"
+                      echo "Mensagem: '$MSG'"
+                      echo "O padrão deve ser: tipo(escopo): mensagem"
+                      exit 1
+                    fi
+                    echo "Commits Validados com sucesso!"
+                  done
+
+            - name: Set up Java 21
+              uses: actions/setup-java@v4
+              with:
+                  java-version: "21"
+                  distribution: "temurin"
+                  cache: "maven"
+
+            - name: Starting MongoDB for Testing
+              run: docker compose --profile test up -d
+
+            - name: Build, Test & Sonar (Driver Service)
+              env:
+                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+              run: |
+                  cd driver-service
+                  mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
+                  -Dsonar.projectKey=joljolionn_sumus_driver-service \
+                  -Dsonar.organization=joljolionn \
+                  -Dsonar.host.url=https://sonarcloud.io \
+                  -Dsonar.qualitygate.wait=false
+
+            - name: Build, Test & Sonar (Passenger Service)
+              env:
+                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+              run: |
+                  cd passenger-service
+                  mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
+                  -Dsonar.projectKey=joljolionn_sumus_passenger-service \
+                  -Dsonar.organization=joljolionn \
+                  -Dsonar.host.url=https://sonarcloud.io \
+                  -Dsonar.qualitygate.wait=false
+
+            - name: Stop containers
+              if: always()
+              run: docker compose --profile db down
